### ISSUE TITLE
Can't load NRRD files with "spacings" in header

### ISSUE THREAD

**Issue by MattTheCuber** [niivue/niivue-vscode#50] opened 2024-03-08 21:50 UTC
This is a very simple image, when I removed the `spacings` header, it works perfectly, when I add the `spacings` header it displays this:

![image](https://github.com/niivue/niivue-vscode/assets/32849887/8c5adb09-8230-4791-8b33-8ed03ce5011c)

Here is a simple example script:
```python
import numpy as np
import nrrd
data = np.random.randint(0, 2, size=(20, 20, 20), dtype=np.uint8)
header = {
    "type": "uint8",
    "dimension": 3,
    "sizes": list(data.shape),
    'encoding': 'gzip',
    "spacings": [1.0, 1.0, 0.625],
}
nrrd.write("data.nrrd", data, header)
```

Here is the file when I cat it:
```bash
> cat data.nrrd
NRRD0005
# This NRRD file was generated by pynrrd
# on 2024-03-08 21:53:01(GMT).
# Complete NRRD file format specification at:
# http://teem.sourceforge.net/nrrd/format.html
type: uint8
dimension: 3
sizes: 20 20 20
encoding: gzip
spacings: 1 1 0.625

m���0
OD�Ubo����I�Ěg|awr���Jg�S ��M���>~?��+�~���\�|�>���������s!����{���������7=w>�y����<]�9��]���{��ds�wG�q��<y��ϯ��x7p��CM&X��������ʻ��d�:���<�p���L��h���l��#��5h;�=��v�
�X�p��:9e
���v�CR\��v0@Q�D� ����,�"����z"[��9N@DiV^��
Ǒ�a�P�x�x��!�n[�I9�I|�Q��c�h}$:�ߗ�p�Q0G��6�0TG�ĕQ$O���k���A����L�������~����׍(b�=I���5
D�����t��9yz�H��-�V���n=&.C�`4�RsITe��
                                      u�s�m����-@t���M�"�a�*H�]GO�
���&�:��}�S�7�tX8D�YU�&�d�                                        �b�q�H���$Z�����#*�A,�
�I��)΄|d���[]����IPf��@��c�ߝڀ�&���
b�y��(�1r��zJBo�f�1[9A�$�ˬ�R_Zg�"����D��Ԥ�%W���S
�_�m�,�=ZuF����F^�P�M��e�I���[]����=����zX%     �[J�>���jKe7��|<77kd�O�"�.�@a6
S                                                                             )�R"�!c�S�pEV}{v;Aït�gjD�#EJ-�R�r=���     $�9%�OG�xCҢl� nYC7-Yq��Y�j��s��CL�W�د�'*�zFE
4�Q/�`#�_�e�����Z�zޤ�J���ۗu��S�jӎe"9���s1�[�_Β�B�FOD�e&gm<�uOx[^/!8Ä5����M�ח5rlL��@�_�6%K/۠X怡��R����_�X=MC�jb����|��mE����ɬ�肆>�&i��H_��;�3�$C=s,M�e�Tf's���D��f�
 �;K����"�ع�wL��-
                 �WT���2c4���`t*���f;X�p�E�    ��ef�L��e}�n��~ � n��0��ٚ9W�ڡ��'��ݣ<i�pΪ��лMg�'��r{���4l�/�MF�Ԉiq��G6B`91~��4S�.H�~�z��� ����R
                                                                                                                                             ]��n��bA��90���^h��y���t@(
```

**Comment by korbinian90** [comment] 2024-03-13 15:14
Thank you for posting this!

I could reproduce the failure to open the image, but I couldn't get it to work by removing the spacings header.
This is quite weird since it works in the web-version without issues: https://niivue.github.io/niivue-vscode/
Maybe there is a problem with handling compression while reading the file...

**Comment by MattTheCuber** [comment] 2024-03-13 22:21
Yeah, I'm not sure. Very strange that the issue didn't resolve when removing the spacings from the header for you...

**Comment by korbinian90** [comment] 2024-03-18 15:58
This issue should be fixed in the new pre-release:
<img width="764" alt="image" src="https://github.com/niivue/niivue-vscode/assets/1307522/23adc088-cf62-43ca-a994-c5855af6f06b">

**Comment by korbinian90** [comment] 2024-03-19 14:15
Let's keep it open for now. I plan to release it soon after some tests (and once I get the release token working again...)

**Closed** 2024-06-06 14:54 UTC
